test_key: ENC[AES256_GCM,data:xekJ8hRXKii0602MLQA=,iv:MWVHtS6/LaAd6DSqOaEauX8DyfmwVtU6lf070bWUNxA=,tag:K9Sq042ScozAQbfa8qQy/g==,type:str]
another_secret: ENC[AES256_GCM,data:1uqP+qEmUg==,iv:rWYiHsMvKeEtSNR6ZU8mFBQqvEZgoSybG/Z6GBkhGkk=,tag:EBLeliHfMaWT2uoUjFQqSg==,type:str]
sops:
    age:
        - recipient: age1ye3hvd0gvus60dc0uu0thy8h5nkw4lvcn53uv2fsp7szksgvfexs6st2qj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUVVQekNNeWoyTm5ETGZG
            bXVBTTlESVUyc3gxVzRPenUrdTRoNW5RTkFBClBQYldIUHBIL20ybTVYa2xVSjBS
            OHlLOFhUVEROa1JIaXh6eUViSjg2UFkKLS0tIHZlUWRqZnEyWmF2ZFk2YUhXRU5H
            SlVVeitwc3FtenNDT0k2aGVQRnp5bjQKUbAXdogkpKiiDnxzL6oSyIBQfDKCL0Ja
            03l3hRQCnbM3cd3h/drzLpXlHcVfFatWw8M4hXK5T9bn+PqHFHNZLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ust3kmy05n4z4x7f5etmctvpmv9gdy7y0mgvnyv6y9fuhm2lu5ysrasleg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyak9YNU9DUmcvSk9mUDl2
            ckJaZGo0dC9tb25HdVlVNENIOFNuT00yZmwwCm0ySThJYjBXUEtkL1lmUkhQR0RC
            OHpXUnJtT3RudjV1dHh6TjlWZ3JtUUkKLS0tIDMvZ29yelJpWjdmNmxJZ0kxQTNF
            cFpZZjN6bDRBZWQ2Slk0NVluSGxlNkEKdsINJVF5tYwfVcU68A4NBb0m6g5Rc0S7
            fataKQIoePwAZNb/2Unrv7gLZrQ8yfFF8gXHN8UpvOTPfvtkqF862Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vyg486rqhv3eyttarhgux7qhyh7p8c93xawkuurr72zkzss4rccq05fydh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOW5HYkJEVXJsWWp3ampz
            K3psRm14SW9rMlZFT1o2WURveWUrRUV3WENZCjVBam90cVNvUGhrUytMNmZYMDZw
            OFZjL2pydkl2UmJ0Q3ltdXZlb1NxU1EKLS0tIEtQcVo4S2ZVSjFaTmlxdTFqQXJT
            c2hnMkh2ZE1CL0V0OWtjdzl1cDg4Z3MKdMaEhy/MZzlssTXnzR3dx/19RF/icyJX
            YHDFkTrCRC0c1XeHZepilvYuaHpe9m4JIYs/kneuTDI5D9vI6A3C8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T08:24:19Z"
    mac: ENC[AES256_GCM,data:SxEOGQSsASOsVp4BZnAl5zYdFP5lr6gu55ojPM3y32+M06+Fz5hK26USbrdLwtUMRGvsLV7TWMEbk1ppzPFajvtF4gqW1tLo7a30gqTXNeH+0NhVT8PSBIL8z3M1VRtcB16vabMdawhS3wlbD0jvzGPhGawQjAMwVtoWZ5EjGx0=,iv:0qDQtvf7QUHNw1Mg6urVXjnqoR4JIvcH3jcNs4eqgQY=,tag:b2HYIReAgQLlV+SxTLbKdg==,type:str]
    pgp:
        - created_at: "2026-03-16T06:19:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2PNXi14PxdAAQ//SQ4PNb3751RsrdPmMPXCqo/ltym8AAGSzN9yCagXTxXS
            gQv+0ShKIcJwsFeufvrfwvkikFV3EGt8kPz7TW3V5hSgCX/2FNXUnbqXOuDjaEgC
            RMVUo1TzrfgX0Mr+OBNsN8qgtwJZfb8ptXidKXQnpqCap0OkU0pep7JiZS4kfpev
            dLKVhjEKJ94wQSsXRvjrXk2OTtQaakJQ8FS7Z1J+ErZOhnuVM8hk3FPbiO53J5ID
            O9Cpnhs0/ahokx/2s6ikLlCYOhy95ZlpVOkDNljAFMY+4ZBOpSmR3pOtqY69kD1L
            Lmfw1SwP28ZFM9U47Oeex4t9tdKcnuB8wBzaXaIESC95cMOt3zndEvm1MOK05vmS
            /FYgj5h+FeLAv19XUIfjFM2uOMHN2BNrHWJTDYWAubTJfEELgOHVrgzOW3kX625I
            8s7jmBUb6J1ZYvclKXkYoX03BduY9q6uPkgc+nA/xOwx+Ot1gVZWV0Zm7D1g4jrr
            4HNq1DQYqkIvmUgfF8Khc4eIlJuxWBEstu3RHrVQGt9lwjOZej9swhA25uh2j0TN
            T/HFiMUE2bWcIRI6YokbB1AdYNVOgUum/hYF2Fcp+zK2Ah9WokTPAoYTxGpdx8HT
            vgl81uWesmAE8ZAUVUZ1QMNfOGkLokkvXqjmR2hL26lc1J9rXlXetSy9X6fl/hnS
            XAHZl9uzz6l/eD+kYhMEvqDJ72+Uyk9nBNDXnjYfkVSNw4eAC7FGKMFIg3b+ylgE
            wtx0BDnyxuA0yo8xVWPOT28omxP9TDxiFtv28002tB3aMcNUYVN6uR4Yby4t
            =feZa
            -----END PGP MESSAGE-----
          fp: 2554AF728296F0DE6C7E65FC2A76355E27FF9075
    unencrypted_suffix: _unencrypted
    version: 3.11.0
