test_key: ENC[AES256_GCM,data:xekJ8hRXKii0602MLQA=,iv:MWVHtS6/LaAd6DSqOaEauX8DyfmwVtU6lf070bWUNxA=,tag:K9Sq042ScozAQbfa8qQy/g==,type:str]
another_secret: ENC[AES256_GCM,data:1uqP+qEmUg==,iv:rWYiHsMvKeEtSNR6ZU8mFBQqvEZgoSybG/Z6GBkhGkk=,tag:EBLeliHfMaWT2uoUjFQqSg==,type:str]
sops:
    age:
        - recipient: age1ye3hvd0gvus60dc0uu0thy8h5nkw4lvcn53uv2fsp7szksgvfexs6st2qj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTm1hSVJnVWZ0LzRFWDVD
            cm9lUTNremxOeTFiRHJtSE1WdTNkQmFYTG1JClBMdnNsd2szU0lGSEdQM3k0SHo3
            SndkSkEvWmJkczc0aTRFZXdhTkxqaVEKLS0tIHVaWWtMWVdnRWlCYTN5NTltN1Zv
            U1Z0Mks5VGZFUjllSWd2dkJMUk1iNkkKGuVuO6p7dChJeU1E+SlwMLWFhlsFZnIn
            tVDEDJcz27gdX73g8nXGlF9HfFKiRsEopbJM9O4nvZf0DG6E7hHIhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ust3kmy05n4z4x7f5etmctvpmv9gdy7y0mgvnyv6y9fuhm2lu5ysrasleg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L0xYTzVFaTI4bGxnTkVv
            dFZ0OVdTenNqUzdHT0ZFZlF1d2lqS2VrWVFBCnByeGxzOFlZcGlMRStQQUpTMHMx
            citKSksxRi8yTkFnS0ExMVRsVEJlSEUKLS0tIHlMOHo4UjhjbEl2RDVFWDFwcnA5
            ZDEza0t5OEdSa0pObFVIZlB3MVFNb2cKmlivOsHOYETX7kgxAjxBC4rlC3xJvBBE
            qvtjx/BoSJogj2WaMfu7KrOBrlVlZXjViEhKAB6U+RM++0v5NPZ/ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T08:24:19Z"
    mac: ENC[AES256_GCM,data:SxEOGQSsASOsVp4BZnAl5zYdFP5lr6gu55ojPM3y32+M06+Fz5hK26USbrdLwtUMRGvsLV7TWMEbk1ppzPFajvtF4gqW1tLo7a30gqTXNeH+0NhVT8PSBIL8z3M1VRtcB16vabMdawhS3wlbD0jvzGPhGawQjAMwVtoWZ5EjGx0=,iv:0qDQtvf7QUHNw1Mg6urVXjnqoR4JIvcH3jcNs4eqgQY=,tag:b2HYIReAgQLlV+SxTLbKdg==,type:str]
    pgp:
        - created_at: "2026-03-13T08:32:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2PNXi14PxdAAQ//VkxrNYQrjRVudp9z8vuq5X8NWHIzz6Y85d0kvAoTOYXy
            yEA5wBOK+DXDy1nbIiTkZoAVQ8nnuQgYsGvtZHjNlhnbFydKTQUhNadl/rd6slso
            YAmifdcYjitow/fqDWJ161IUUml2wF/eO8pNHhbJnCqZVVeeiILmB7Ko5sXrmIDg
            ZO7dK+oFk3SIF7l0tGrPFWYrN2c0TNVGED5IC3tJ3LitcIRBZLEy5OruDOwATeTf
            FPP+I9tUNiybKWtUfcjnnaZvDl7wXsI6h0Lf3AHQC0TFTWJQfKSdrbEWitcgvplW
            nTY96P+JEQIfU/uWc5FATUxfQ4lYWnZY6OCEQ1Cih1ZxvcYFZG4AFTdSzFQRzjPU
            Q1N1JqNX9xP3IWGVP7KxMcXbdb0dKbcKyY546eMwXt8LzeGGG0IeG2aeqITOKsYZ
            lMeHn5p+HcJOI/uHL8xqEA5Ho7pe2rT+4ZL0gF8Rv1oDrI8tbA2FpVFrXMNNpo7x
            uTnD/BqMPUq1ODxnasEFWipD70A0groM2cM98vQCZiTAOSA1KaMu+Zn6mlpVRpip
            5P1Yg498Sbn8NUYlV+5+OwJpurt024NFQRLpM+hzmBzJVj/xDXaPdmYdF17oEf6r
            9069e4E4s1JrsvDkfaFLeFFwLq/CO/+JKk3U8tQ5NWvpKkdBziXXf3RmrBgNXYPS
            XAH4fOjih6f8prNg8jeuv/sMQuMD7O3EOXYiMFBzhjiKn6KUzAWPL4UI/q9FaJzs
            urZsU64GOicg2JXv5uogJfNr1mFDIE+bdOqqc2C8uVfLEAdeLH9r0HqcP2e1
            =McdW
            -----END PGP MESSAGE-----
          fp: 2554AF728296F0DE6C7E65FC2A76355E27FF9075
    unencrypted_suffix: _unencrypted
    version: 3.11.0
