keys:
  # Admin (Nitrokey GPG and emergency age key)
  - &admin "2554AF728296F0DE6C7E65FC2A76355E27FF9075"
  - &recovery "age1ye3hvd0gvus60dc0uu0thy8h5nkw4lvcn53uv2fsp7szksgvfexs6st2qj"
  # Hosts
  - &desktop "age1ust3kmy05n4z4x7f5etmctvpmv9gdy7y0mgvnyv6y9fuhm2lu5ysrasleg"
  - &vps "age1vyg486rqhv3eyttarhgux7qhyh7p8c93xawkuurr72zkzss4rccq05fydh"

creation_rules:
  - path_regex: secrets/common\.sops\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *recovery
          - *desktop
          - *vps
          # - *homeserver
          # - *work

  - path_regex: nixos/hosts/desktop/secrets\.sops\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *recovery
          - *desktop

  - path_regex: nixos/hosts/vps/secrets\.sops\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *recovery
          - *vps
