test_key: ENC[AES256_GCM,data:oms+vN36,iv:H/bZlRWST519P1PkPKhmbG/Bu1xGKL5Mhbwq2t0JRbQ=,tag:idjqOlSeQP6nAjRvzvs2QA==,type:str]
sops:
    age:
        - recipient: age1ye3hvd0gvus60dc0uu0thy8h5nkw4lvcn53uv2fsp7szksgvfexs6st2qj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVGcyMDk5dXREelN3NHNq
            bHVtd1lhbFIydjNiTW15Z2MxM01jZVRvdEN3CnFuekdwdVhlYjB3bnNsdkVjRVZr
            a2ZmTUFIWEVVV21jRzVWYXpDMWxKN1kKLS0tIDJOb3d5Nm5JbDNSSEpMSTJyZW1x
            ejZRL3pESHJRSU0vQzhvc2JSVU9QTmcKEHNf6yd9sO0ZCwfEr80vfqL2BIYXc7gm
            eUTPOZv3O7C438FATDmFH05wbSPelj/PsEPUU4VET54vSkgx99c4dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:25:05Z"
    mac: ENC[AES256_GCM,data:XKz3J9L6OL9crIFW8dd56OBgvwigWChPVthKO84Q97AC9zwgY9jSCwyJFTzj6u7Xc6lo8SzUsQeD66t8b6K/gpOf8dj9zAqk1xRuAoH7ZesNyU8AzWzi5UDEclHVcCx8j3kExuu/LH1o7VucqbvegkzSh/1QOBi0H/V6hTP7+Go=,iv:MnZOCaft4vbip/zc44+lEBKC9FRIERZeatkTusGqO+I=,tag:4yIIiqxl7VZUjSLHgDGGXw==,type:str]
    pgp:
        - created_at: "2026-03-15T17:24:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2PNXi14PxdAARAAgslpNjdOWYBel16rhDac4kJmM7bNFxm243TwOEJmovx1
            PEeVH2qlZvbu3aeHiyCGsbhU659shyM6xmZe8Sjxs4S0OSnBZMKhJnoyZ5Hk9MSV
            /XOGjaSaJASGfUNEYRWdg6X0gsUVjTZNw758zhpFnzNqf1O3B2u7e4M56pKFl1NQ
            Hcpv5/CJ5gLX6KBUb4KPcMFborWwOU930qjgOdpSz4c2QVx0ikwMEtfAQoJZIZA3
            kF28EUp2h8x6TfNLqZox2xFr9lOJPHdn108dMIKL3E4FIQw8Rve7u2pASGYOF51e
            y9KLVKhLENSQbq2pfYHejg370L3+3bZd7xq4svY36Nl5DN6vsZpQSb6Jb5F+dYQe
            AqnXsCy7bZgrYfym3KxhbJg6giHfXb5UIphgMit1OI4Qak3HVwUwzV5E1dh7ECiS
            /J7kU+Ai3nI2RwrDF7PUt31gF1y7x8QIRyHZoFRI7bq40fCdEOd2xmXfxW/N7gvx
            QxLQaR5Fh3/a13FXLlm2pa88cOoywig+kt5AxL1jXm9OsK9TP2VMVAIGMUFA0Gb9
            /dmVm1aJhlvhxTIXkYvEzHgFHvxNHxAgXhfob3bNHrTcXgD43RgrLYxK7l3wPkU6
            czCTqooPMrCbjwWwGCbh5AlpcRuTedbmvbNnEu/FET1x94F3uIGkJJLM729fmYzS
            XgEt2C5L0ybAzEu3rMkIiM7PlkL3RYsUkq21wFbJBVl0MHkh67hAKbu9CJDSSQPX
            GU3gG3iAlAxHL7boM1m1DoxawtA+Q+jWxHx5gnRcUItz5suJvM76hAb0e82dOTY=
            =hfrm
            -----END PGP MESSAGE-----
          fp: 2554AF728296F0DE6C7E65FC2A76355E27FF9075
    unencrypted_suffix: _unencrypted
    version: 3.12.1
