test_value: ENC[AES256_GCM,data:zzxPQxsl,iv:j9m//9vvVfz4I5FSc6Gtg9HFKSaGd+3q7CKcJPgnmvE=,tag:uXpGOuUePWNilbOqVUaP7A==,type:str]
sops:
    age:
        - recipient: age1ye3hvd0gvus60dc0uu0thy8h5nkw4lvcn53uv2fsp7szksgvfexs6st2qj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSXhwM1JPdmlGOXExbUVh
            MHhHZU54N2NxbU9kQXNENFREYUFKd0o0M21VClR5TlExMy9GZzl1NWM2eUJETDNs
            em42UGkyYTF1T0x1RXJYb2VuQ1dJYjgKLS0tIHE1QW41bUY1dVV2cVQ4Y3JNUDNE
            UjRHQ0MwN0xUU0tia2hrVGQvQW5FT00KbiPvTabR9ZQnh/akGO0jeDr0rqiZUFVK
            6NdOiK3URX6DrAO332DXfjfva7gJIIp6wfFbYaNuJEnlCbqwiKHKqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ust3kmy05n4z4x7f5etmctvpmv9gdy7y0mgvnyv6y9fuhm2lu5ysrasleg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbTB3Wk5KaDY3NThCbUZL
            N3dFSmRqVmxYQWlpT3laWEtrci8xZ2ZKNFIwCjFXVzlmcXBTa1NBUkZ2eU1LeXBm
            VDR6NG5kZlNLaUIzKzR0eWFJVFcwQkEKLS0tIFdVSmpvZFpreGJBMnY2MURrVDcr
            ajYyRzVWZGhyRjVlNldBVFhoMUhmU1EKKiLKgTKUn5Dy8C9R5Vno6dIyMrdVCg/5
            O2mqwALmffJDKxbcu5btlIeMM1CzNcHy9gaQt4PMcaZy3DL4+A2ybA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:18:04Z"
    mac: ENC[AES256_GCM,data:do5474SXuAYgZKJ9QHXmKmnVlhV5wDWMi2CskPmESFI9BuWfs2XJl8rfIC8odR0FCXP5zxkSE9XR0Fmlh4fJSGdLbpm3ZEJzUe3r5CYRMoovY2dYNhSGeIGoe/wNu8H7rwqK9RlFsBWKQiPQIzh+f8erox7OW3QrQ1LWdMVWNqE=,iv:BeAoKU+KY0x/DRKXzD6rbcvzRAXKljL3liftO1C0E4s=,tag:5E2GjZz4rS2eO5rQ5ELdDw==,type:str]
    pgp:
        - created_at: "2026-03-15T18:27:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2PNXi14PxdAAQ//bTlbydLIkb1bgm74SUr3h3rYULDxUl84T6KP/r3m/nYq
            DLyaT42B/sg5eFsU15joLESWZKV3DndCMpDV10JqmTvFXANHk0mV/vcTEPOGLUTq
            CHpzlKO30BY1RskAvpIgYYE+dB+iaOUkUyoHiohQSKlIoxTwewM4mjsWuSm31UT/
            RrDmS+9aBDa9NnO5RM0gBJRWJ6RaN1DCbJpQjv4DwLuagE1ValkaQSkd9JiT3lUZ
            woloFZ+wcmGXJj/p3dYhPkIHaQLsY5gxtS8juACEuk8oSTR7q/Sa61rX7/iPJgQl
            Zx+tcj5MTJHDLdYlHur1WMnxpJ9KsJj0j5VCaDW6KVBuWxSBOdW+YMgrzLi2Ydht
            alDNNaOERIegDuwSzq/XIKEogMgliMpdhUlm4YCHFvmmWvLX5Z1lG1ahzkjvt+va
            R6MtaqaIcFcvKMqZgthviZrvk5nhMgGX89wweZO4d2rBhV6nm98llMyUbkLTgKeO
            FlD/ZOke/lsL+9M7EoUoTGKWLKe4P/n0Q1vS4mycQmvrI8VVLMLCdkBFknBo+ITd
            Szqpzi2HvtlJRAw+DR7gUb8afLaKGW4H7NT5WNOA+N2zOiZfi8w9x4yOI34/bmnR
            zolafByVTtlmTrp/BUBj55dRrRuFUiawYWkajVPeM/TAJI1VwwpcOo8ZVD1+P1HS
            XgF+FQIsdqBV0x4dXT+Spu1hsDQ2F2s5o4oyrlWD3p7oMq/ptUlQjhWelF8lrzsL
            0FC/7sgJtl0HXHYxbFtnfn2bPJDjocYYru2O75KHrS6XmmeS0m/jnRuruB8HETQ=
            =qceq
            -----END PGP MESSAGE-----
          fp: 2554AF728296F0DE6C7E65FC2A76355E27FF9075
    unencrypted_suffix: _unencrypted
    version: 3.12.1
