#!/usr/bin/env bash
set -euo pipefail

echo "Running statix check"
statix check . -i .direnv

echo "Running deadnix"
deadnix . --exclude .direnv

echo "Running nix flake check"
nix flake check --no-build

echo "All checks passed"
