test_value: ENC[AES256_GCM,data:oa6/mtbg,iv:dKb2jdnjiberJRGSPYW+IZ92Q7onSW6qbnFjIOK4a3A=,tag:pltLu2u2UqXToEjUz3r1VA==,type:str]
sops:
    age:
        - recipient: age1ye3hvd0gvus60dc0uu0thy8h5nkw4lvcn53uv2fsp7szksgvfexs6st2qj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWFORTZrM0dIdGhKeDB3
            RGxlSlF3cUQrWVZMbElMeGdHem8zWklnU0Z3Cmk1ZU93SjlheDRlRS81bEh3Wllz
            UE9ZMm43eVdkRGZYNFJrNHcvR00vY2sKLS0tIHZ0VmdpZDJQcFZzYWxLSDhnak0x
            THNJTjNTTlU1SjFjeWJXL0RHOUg3ZWcKBqvvtZBYvqL1Ap8TDaBdwK+pJ0CE4JQg
            4juAg55MUd+NnxasDRewshe8fzbHsluI2O33kdiae4mN4WshXD8OIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:25:22Z"
    mac: ENC[AES256_GCM,data:zr1Ub/u0K1dzMs4iu9p7aGWJNA3QwVnwMJ0Y48DECtqir8ZAMjTbZyFgrYJkX2ef+JG7eDpveyzSjUFjCwQJCkyU6hWImTQ4sPocD2w8o62LI4YP1GDomPN93mGXc7YvgDk9F+1GjxL3AOO7ByYQUn45A+KFHx2dgpwK3OQfmWc=,iv:UkeW0el6kIAs7t/hYhgtPjlYy8Mq+l3QsSjrxrw0LI4=,tag:swzd6VOka0DWKEkPiLdsuw==,type:str]
    pgp:
        - created_at: "2026-03-15T17:25:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2PNXi14PxdAAQ/+JpvzZYyp/G7TOGKAj/x0/J4gdsgnbe3n0wvofSNFQu9K
            zwDsbkyyIgWQKQ8VTg3QUuNI3lIrlR+9ApFdif9+ntI++n20g80HOVjp5LuoCUV/
            YTKSK34XlfqU+G7sHl1rXp/KOVT9dMUvWGyO1IKP6jeH/07meADapeqmLL4bdw4y
            +mNm7fJkxyX0moMmWsLpwIK8emIBI+h95VaztgabAmwoHHBbTfXM0vMy23BsxOk1
            C3M5vi98ESySmGw1obS5y8B/o421OPkY8+qPm+hBplntKpawyVfRJ1vg8unIX71v
            5T/GZamzn5gRLSfs3E6H6jrp7j0/6L9Cr4ffxUKKCsYOT002r6b1fg+E1pCvHEm4
            Aay/HUdqG+onRHj2Wb+ZoAfzmAQkJYp1MlJKS0IHFgKUfxpN/1tFtbvmEzMXQL26
            waqRugRXnorNmW4BQVT4F/9CrPD0ig0ZhwbhMaYjp/9SDm1C3lFHH1Rq57JC4mxN
            rnN0m3z7bdo71S/WWr/aHNhrccJ1RFfHZ/mGJr3x8KD8+ieA7vewYXeJT4EacJN+
            CkfVauQFi4xSg4fLR4+hFfQdi0IfTYbZk9Jt39uWj+0LGmFmUZv7TfgxuWIXP10U
            g00tLoGYB69Q3QYutUna8rMTX/ZTYMFmx0I/sPI5BlwXqeEbmyqsoEkEk6uYjx7S
            XgH5ul3jPWqm4wS3OkvvnUenXPtec4TH3bJWOXR5CoUVOc/oN0rwbVg4P3PRW09X
            Ng/d6V955NIYFDcY90hc70aH4IoZ5K4BSJITGcvoP5uRsSOe6fgg+ZGl0zBum24=
            =bKA3
            -----END PGP MESSAGE-----
          fp: 2554AF728296F0DE6C7E65FC2A76355E27FF9075
    unencrypted_suffix: _unencrypted
    version: 3.12.1
